-- Add explicit ingredient lists to every menu description.

UPDATE public.menu_items AS menu
SET description = descriptions.description
FROM (VALUES
  ('item-001', 'Slow-braised oxtail and tripe in a rich, creamy peanut sauce with eggplant, banana blossom, and string beans. Served with bagoong alamang on the side. Ingredients: oxtail, tripe, peanut butter, eggplant, banana blossom, string beans, bagoong alamang, garlic, onion, and spices.'),
  ('item-002', 'Tender beef chunks braised in a tomato-based sauce with liver spread, bell peppers, olives, and potatoes. Rich, hearty, and deeply savory. Ingredients: beef, tomato sauce, liver spread, bell peppers, olives, potatoes, garlic, onion, and spices.'),
  ('item-003', 'Fork-tender beef larded with fat and braised in a tangy tomato-soy sauce with potatoes and carrots. A Filipino fiesta classic. Ingredients: beef, beef fat, tomato sauce, soy sauce, potatoes, carrots, garlic, onion, and spices.'),
  ('item-004', 'Thinly sliced beef sirloin marinated in soy sauce and calamansi, pan-fried and topped with caramelized onion rings. Ingredients: beef sirloin, soy sauce, calamansi, onions, garlic, cooking oil, and black pepper.'),
  ('item-005', 'Deep-fried pork belly with impossibly crispy skin and juicy, flavorful meat inside. Served with homemade liver sauce and spiced vinegar. Ingredients: pork belly, liver sauce, vinegar, garlic, chili, salt, and pepper.'),
  ('item-006', 'Classic Filipino adobo elevated with creamy coconut milk — pork belly braised in vinegar, soy sauce, garlic, and bay leaves, finished with gata. Ingredients: pork belly, coconut milk, vinegar, soy sauce, garlic, bay leaves, onion, and black pepper.'),
  ('item-007', 'Sour tamarind broth with tender pork ribs, radish, eggplant, string beans, and kangkong. A comforting Filipino sour soup for the whole family. Ingredients: pork ribs, tamarind, radish, eggplant, string beans, kangkong, tomatoes, onion, and fish sauce.'),
  ('item-008', 'Whole pork knuckle boiled until tender then deep-fried to a perfect golden crisp. A showstopping centerpiece for any celebration. Ingredients: pork knuckle, garlic, bay leaves, peppercorns, salt, and cooking oil.'),
  ('item-009', 'Bacolod-style grilled chicken marinated in lemongrass, calamansi, and annatto oil. Smoky, tangy, and utterly addictive. Ingredients: chicken, lemongrass, calamansi, annatto oil, garlic, ginger, vinegar, and spices.'),
  ('item-010', 'Chicken pieces braised in a vibrant tomato-based sauce with potatoes, carrots, bell peppers, and green peas. A Filipino household staple. Ingredients: chicken, tomato sauce, potatoes, carrots, bell peppers, green peas, garlic, onion, and spices.'),
  ('item-011', 'Light ginger-based chicken soup with green papaya wedges and malunggay leaves. Nourishing, fragrant, and deeply comforting. Ingredients: chicken, ginger, green papaya, malunggay leaves, garlic, onion, and fish sauce.'),
  ('item-012', 'Marinated chicken thigh skewers grilled over charcoal with a sweet-savory Filipino BBQ glaze. A crowd favorite at every party. Ingredients: chicken thighs, soy sauce, banana ketchup, brown sugar, garlic, calamansi, and bamboo skewers.'),
  ('item-013', 'Fresh Spanish mackerel steaks marinated in calamansi, soy sauce, and garlic, then grilled to perfection. Served with sawsawan. Ingredients: Spanish mackerel, calamansi, soy sauce, garlic, cooking oil, and sawsawan.'),
  ('item-014', 'Jumbo prawns sautéed in a fragrant garlic butter sauce with a hint of calamansi and chili. Rich, buttery, and irresistible. Ingredients: prawns, butter, garlic, calamansi, chili, parsley, and black pepper.'),
  ('item-015', 'A luxurious version of the classic — mixed seafood (shrimp, squid, scallops, mussels) in a velvety peanut sauce with fresh vegetables. Ingredients: shrimp, squid, scallops, mussels, peanut butter, eggplant, banana blossom, string beans, and bagoong alamang.'),
  ('item-016', 'Stir-fried egg noodles with pork, chicken, shrimp, cabbage, carrots, and snap peas in a savory soy-oyster sauce. A Filipino birthday staple. Ingredients: egg noodles, pork, chicken, shrimp, cabbage, carrots, snap peas, soy sauce, oyster sauce, garlic, and onion.'),
  ('item-017', 'Elbow macaroni in a sweet Filipino-style Bolognese topped with creamy béchamel sauce and baked until golden. Kids and adults love it equally. Ingredients: elbow macaroni, ground beef, tomato sauce, banana ketchup, cheddar cheese, milk, butter, flour, and onions.'),
  ('item-018', 'Traditional Filipino sticky rice cake made with glutinous rice, brown sugar, and coconut milk, topped with caramelized latik (coconut curds). Ingredients: glutinous rice, coconut milk, brown sugar, coconut cream, and salt.'),
  ('item-019', 'Silky-smooth steamed custard made with egg yolks, condensed milk, and evaporated milk, crowned with a rich amber caramel. The queen of Filipino desserts. Ingredients: egg yolks, condensed milk, evaporated milk, granulated sugar, and vanilla.'),
  ('item-020', 'The ultimate Filipino shaved ice dessert — a colorful mix of sweetened beans, jellies, kaong, macapuno, ube halaya, leche flan, and creamy ube ice cream. Ingredients: shaved ice, sweetened beans, jellies, kaong, macapuno, ube halaya, leche flan, ube ice cream, and evaporated milk.'),
  ('item-021', 'Complete fiesta package: 1 Lechon Kawali tray + 1 Chicken Inasal tray + 1 Pancit Canton tray + 1 Leche Flan. Perfect for 25–30 guests. Ingredients: pork belly, chicken, egg noodles, shrimp, vegetables, soy sauce, calamansi, annatto oil, eggs, condensed milk, and evaporated milk.'),
  ('item-022', 'Premium handaan package: 1 Kare-Kare tray + 1 Pork Sinigang tray + 1 Chicken Afritada tray + 1 Biko. Ideal for intimate family gatherings of 20–25. Ingredients: oxtail, tripe, peanuts, pork ribs, tamarind, chicken, tomato sauce, vegetables, glutinous rice, coconut milk, and brown sugar.'),
  ('item-023', 'A classic Ilocano vegetable medley of ampalaya, eggplant, okra, sitaw, squash, and tomatoes sauteed in shrimp paste (bagoong). Hearty, flavorful, and nutritious. Ingredients: ampalaya, eggplant, okra, sitaw, squash, tomatoes, bagoong alamang, garlic, and onion.'),
  ('item-024', 'A colorful stir-fry of cabbage, carrots, bell peppers, snap peas, cauliflower, and quail eggs in a savory oyster sauce. Light, vibrant, and crowd-pleasing. Ingredients: cabbage, carrots, bell peppers, snap peas, cauliflower, quail eggs, oyster sauce, garlic, and onion.'),
  ('item-025', 'Refreshing chilled drink made with young coconut strips, pandan-flavored jelly, and creamy coconut milk. A classic Filipino party cooler served in a large dispenser. Ingredients: young coconut, pandan jelly, coconut milk, sugar, and ice.'),
  ('item-026', 'Classic Filipino street drink with chewy sago pearls, cubed gulaman (agar jelly), and sweet brown sugar syrup. Served cold in a large pitcher. Ingredients: sago pearls, gulaman, brown sugar, water, and ice.'),
  ('item-027', 'Freshly squeezed calamansi juice sweetened with pure cane sugar and served chilled. Bright, citrusy, and perfectly refreshing for any celebration. Ingredients: calamansi juice, cane sugar, water, and ice.'),
  ('item-028', 'Traditional Filipino ginger tea brewed strong and served over ice with a touch of honey and calamansi. Warming, soothing, and uniquely Filipino. Ingredients: fresh ginger, honey, calamansi, water, and ice.')
) AS descriptions(id, description)
WHERE menu.id = descriptions.id;