-- Seed the ingredient catalog used by the current menu and connect each
-- ingredient to the dishes that use it. Stock quantities must be counted by
-- the restaurant before they are treated as accurate.

ALTER TABLE public.inventory_items
  ADD COLUMN IF NOT EXISTS is_counted BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS public.menu_item_ingredients (
  menu_item_id TEXT NOT NULL REFERENCES public.menu_items(id) ON DELETE CASCADE,
  inventory_item_id TEXT NOT NULL REFERENCES public.inventory_items(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (menu_item_id, inventory_item_id)
);

CREATE INDEX IF NOT EXISTS idx_menu_item_ingredients_inventory_item_id
  ON public.menu_item_ingredients(inventory_item_id);

ALTER TABLE public.menu_item_ingredients ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin_manage_menu_item_ingredients"
  ON public.menu_item_ingredients;
CREATE POLICY "admin_manage_menu_item_ingredients"
  ON public.menu_item_ingredients
  FOR ALL
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

INSERT INTO public.inventory_items
  (id, name, unit, current_stock, reorder_level, status, is_counted)
VALUES
  ('inv-001', 'Pork Belly', 'kg', 0, 15, 'Not Counted', false),
  ('inv-002', 'Chicken Thigh', 'kg', 0, 20, 'Not Counted', false),
  ('inv-003', 'Beef Oxtail', 'kg', 0, 10, 'Not Counted', false),
  ('inv-004', 'Shrimp', 'kg', 0, 8, 'Not Counted', false),
  ('inv-005', 'Coconut Milk', 'L', 0, 10, 'Not Counted', false),
  ('inv-006', 'Peanut Butter', 'kg', 0, 5, 'Not Counted', false),
  ('inv-007', 'Glutinous Rice', 'kg', 0, 10, 'Not Counted', false),
  ('inv-008', 'Aluminum Trays', 'pcs', 0, 30, 'Not Counted', false),
  ('ing-tripe', 'Beef Tripe', 'kg', 0, 3, 'Not Counted', false),
  ('ing-eggplant', 'Eggplant', 'kg', 0, 3, 'Not Counted', false),
  ('ing-banana-blossom', 'Banana Blossom', 'kg', 0, 2, 'Not Counted', false),
  ('ing-string-beans', 'String Beans (Sitaw)', 'kg', 0, 2, 'Not Counted', false),
  ('ing-bagoong-alamang', 'Bagoong Alamang', 'kg', 0, 1, 'Not Counted', false),
  ('ing-garlic', 'Garlic', 'kg', 0, 1, 'Not Counted', false),
  ('ing-onion', 'Onion', 'kg', 0, 2, 'Not Counted', false),
  ('ing-spices', 'Mixed Spices', 'pack', 0, 1, 'Not Counted', false),
  ('ing-beef', 'Beef', 'kg', 0, 5, 'Not Counted', false),
  ('ing-tomato-sauce', 'Tomato Sauce', 'L', 0, 2, 'Not Counted', false),
  ('ing-liver-spread', 'Liver Spread', 'kg', 0, 1, 'Not Counted', false),
  ('ing-bell-peppers', 'Bell Peppers', 'kg', 0, 2, 'Not Counted', false),
  ('ing-olives', 'Olives', 'kg', 0, 1, 'Not Counted', false),
  ('ing-potatoes', 'Potatoes', 'kg', 0, 3, 'Not Counted', false),
  ('ing-beef-fat', 'Beef Fat', 'kg', 0, 1, 'Not Counted', false),
  ('ing-soy-sauce', 'Soy Sauce', 'L', 0, 2, 'Not Counted', false),
  ('ing-carrots', 'Carrots', 'kg', 0, 2, 'Not Counted', false),
  ('ing-calamansi', 'Calamansi', 'kg', 0, 2, 'Not Counted', false),
  ('ing-beef-sirloin', 'Beef Sirloin', 'kg', 0, 3, 'Not Counted', false),
  ('ing-cooking-oil', 'Cooking Oil', 'L', 0, 3, 'Not Counted', false),
  ('ing-black-pepper', 'Black Pepper', 'pack', 0, 1, 'Not Counted', false),
  ('ing-liver-sauce', 'Liver Sauce', 'L', 0, 1, 'Not Counted', false),
  ('ing-vinegar', 'Vinegar', 'L', 0, 2, 'Not Counted', false),
  ('ing-chili', 'Chili', 'kg', 0, 1, 'Not Counted', false),
  ('ing-salt', 'Salt', 'kg', 0, 1, 'Not Counted', false),
  ('ing-bay-leaves', 'Bay Leaves', 'pack', 0, 1, 'Not Counted', false),
  ('ing-pork-ribs', 'Pork Ribs', 'kg', 0, 3, 'Not Counted', false),
  ('ing-tamarind', 'Tamarind', 'kg', 0, 1, 'Not Counted', false),
  ('ing-radish', 'Radish', 'kg', 0, 2, 'Not Counted', false),
  ('ing-kangkong', 'Kangkong', 'kg', 0, 1, 'Not Counted', false),
  ('ing-tomatoes', 'Tomatoes', 'kg', 0, 2, 'Not Counted', false),
  ('ing-fish-sauce', 'Fish Sauce (Patis)', 'L', 0, 1, 'Not Counted', false),
  ('ing-pork-knuckle', 'Pork Knuckle', 'pcs', 0, 2, 'Not Counted', false),
  ('ing-peppercorns', 'Peppercorns', 'pack', 0, 1, 'Not Counted', false),
  ('ing-lemongrass', 'Lemongrass', 'kg', 0, 1, 'Not Counted', false),
  ('ing-annatto-oil', 'Annatto Oil', 'L', 0, 1, 'Not Counted', false),
  ('ing-ginger', 'Ginger', 'kg', 0, 1, 'Not Counted', false),
  ('ing-green-papaya', 'Green Papaya', 'pcs', 0, 2, 'Not Counted', false),
  ('ing-malunggay', 'Malunggay Leaves', 'kg', 0, 1, 'Not Counted', false),
  ('ing-green-peas', 'Green Peas', 'kg', 0, 1, 'Not Counted', false),
  ('ing-banana-ketchup', 'Banana Ketchup', 'L', 0, 1, 'Not Counted', false),
  ('ing-brown-sugar', 'Brown Sugar', 'kg', 0, 2, 'Not Counted', false),
  ('ing-bamboo-skewers', 'Bamboo Skewers', 'pcs', 0, 50, 'Not Counted', false),
  ('ing-spanish-mackerel', 'Spanish Mackerel (Tanigue)', 'kg', 0, 2, 'Not Counted', false),
  ('ing-sawsawan', 'Sawsawan', 'L', 0, 1, 'Not Counted', false),
  ('ing-butter', 'Butter', 'kg', 0, 1, 'Not Counted', false),
  ('ing-parsley', 'Parsley', 'bunch', 0, 1, 'Not Counted', false),
  ('ing-squid', 'Squid', 'kg', 0, 2, 'Not Counted', false),
  ('ing-scallops', 'Scallops', 'kg', 0, 1, 'Not Counted', false),
  ('ing-mussels', 'Mussels', 'kg', 0, 2, 'Not Counted', false),
  ('ing-egg-noodles', 'Egg Noodles', 'kg', 0, 2, 'Not Counted', false),
  ('ing-cabbage', 'Cabbage', 'kg', 0, 2, 'Not Counted', false),
  ('ing-snap-peas', 'Snap Peas', 'kg', 0, 1, 'Not Counted', false),
  ('ing-oyster-sauce', 'Oyster Sauce', 'L', 0, 1, 'Not Counted', false),
  ('ing-elbow-macaroni', 'Elbow Macaroni', 'kg', 0, 2, 'Not Counted', false),
  ('ing-ground-beef', 'Ground Beef', 'kg', 0, 2, 'Not Counted', false),
  ('ing-cheddar-cheese', 'Cheddar Cheese', 'kg', 0, 1, 'Not Counted', false),
  ('ing-milk', 'Milk', 'L', 0, 2, 'Not Counted', false),
  ('ing-flour', 'Flour', 'kg', 0, 2, 'Not Counted', false),
  ('ing-coconut-cream', 'Coconut Cream', 'L', 0, 1, 'Not Counted', false),
  ('ing-egg-yolks', 'Egg Yolks', 'pcs', 0, 24, 'Not Counted', false),
  ('ing-condensed-milk', 'Condensed Milk', 'can', 0, 4, 'Not Counted', false),
  ('ing-evaporated-milk', 'Evaporated Milk', 'can', 0, 4, 'Not Counted', false),
  ('ing-granulated-sugar', 'Granulated Sugar', 'kg', 0, 2, 'Not Counted', false),
  ('ing-vanilla', 'Vanilla', 'bottle', 0, 1, 'Not Counted', false),
  ('ing-mixed-vegetables', 'Mixed Vegetables', 'kg', 0, 2, 'Not Counted', false),
  ('ing-shaved-ice', 'Shaved Ice', 'kg', 0, 5, 'Not Counted', false),
  ('ing-sweetened-beans', 'Sweetened Beans', 'kg', 0, 1, 'Not Counted', false),
  ('ing-jellies', 'Assorted Jellies', 'kg', 0, 1, 'Not Counted', false),
  ('ing-kaong', 'Kaong', 'kg', 0, 1, 'Not Counted', false),
  ('ing-macapuno', 'Macapuno', 'kg', 0, 1, 'Not Counted', false),
  ('ing-ube-halaya', 'Ube Halaya', 'kg', 0, 1, 'Not Counted', false),
  ('ing-ube-ice-cream', 'Ube Ice Cream', 'L', 0, 2, 'Not Counted', false),
  ('ing-eggs', 'Eggs', 'pcs', 0, 24, 'Not Counted', false),
  ('ing-peanuts', 'Peanuts', 'kg', 0, 1, 'Not Counted', false),
  ('ing-ampalaya', 'Ampalaya (Bitter Melon)', 'kg', 0, 1, 'Not Counted', false),
  ('ing-okra', 'Okra', 'kg', 0, 1, 'Not Counted', false),
  ('ing-squash', 'Squash', 'kg', 0, 2, 'Not Counted', false),
  ('ing-cauliflower', 'Cauliflower', 'kg', 0, 1, 'Not Counted', false),
  ('ing-quail-eggs', 'Quail Eggs', 'pcs', 0, 24, 'Not Counted', false),
  ('ing-young-coconut', 'Young Coconut', 'pcs', 0, 5, 'Not Counted', false),
  ('ing-pandan-jelly', 'Pandan Jelly', 'kg', 0, 1, 'Not Counted', false),
  ('ing-sugar', 'Sugar', 'kg', 0, 2, 'Not Counted', false),
  ('ing-ice', 'Ice', 'kg', 0, 5, 'Not Counted', false),
  ('ing-sago-pearls', 'Sago Pearls', 'kg', 0, 1, 'Not Counted', false),
  ('ing-gulaman', 'Gulaman', 'kg', 0, 1, 'Not Counted', false),
  ('ing-water', 'Water', 'L', 0, 10, 'Not Counted', false),
  ('ing-calamansi-juice', 'Calamansi Juice', 'L', 0, 2, 'Not Counted', false),
  ('ing-cane-sugar', 'Cane Sugar', 'kg', 0, 2, 'Not Counted', false),
  ('ing-honey', 'Honey', 'L', 0, 1, 'Not Counted', false)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    unit = EXCLUDED.unit;

WITH ingredient_menu_links (ingredient_id, menu_ids) AS (
  VALUES
    ('inv-003', 'item-001,item-022'),
    ('ing-tripe', 'item-001,item-022'),
    ('inv-006', 'item-001,item-015'),
    ('ing-eggplant', 'item-001,item-007,item-015,item-023'),
    ('ing-banana-blossom', 'item-001,item-015'),
    ('ing-string-beans', 'item-001,item-007,item-015,item-023'),
    ('ing-bagoong-alamang', 'item-001,item-015,item-023'),
    ('ing-garlic', 'item-001,item-002,item-003,item-004,item-005,item-006,item-008,item-009,item-010,item-011,item-012,item-013,item-014,item-016,item-023,item-024'),
    ('ing-onion', 'item-001,item-002,item-003,item-004,item-006,item-007,item-010,item-011,item-016,item-017,item-023,item-024'),
    ('ing-spices', 'item-001,item-002,item-003,item-009,item-010'),
    ('ing-beef', 'item-002,item-003'),
    ('ing-tomato-sauce', 'item-002,item-003,item-010,item-017,item-022'),
    ('ing-liver-spread', 'item-002'),
    ('ing-bell-peppers', 'item-002,item-010,item-024'),
    ('ing-olives', 'item-002'),
    ('ing-potatoes', 'item-002,item-003,item-010'),
    ('ing-beef-fat', 'item-003'),
    ('ing-soy-sauce', 'item-003,item-004,item-006,item-012,item-013,item-016,item-021'),
    ('ing-carrots', 'item-003,item-010,item-016,item-024'),
    ('ing-calamansi', 'item-004,item-009,item-012,item-013,item-014,item-021,item-027,item-028'),
    ('ing-beef-sirloin', 'item-004'),
    ('ing-cooking-oil', 'item-004,item-008,item-013'),
    ('ing-black-pepper', 'item-004,item-006,item-014'),
    ('inv-001', 'item-005,item-006,item-021'),
    ('ing-liver-sauce', 'item-005'),
    ('ing-vinegar', 'item-005,item-006,item-009'),
    ('ing-chili', 'item-005,item-014'),
    ('ing-salt', 'item-005,item-008,item-018'),
    ('ing-bay-leaves', 'item-006,item-008'),
    ('ing-pork-ribs', 'item-007,item-022'),
    ('ing-tamarind', 'item-007,item-022'),
    ('ing-radish', 'item-007'),
    ('ing-kangkong', 'item-007'),
    ('ing-tomatoes', 'item-007,item-023'),
    ('ing-fish-sauce', 'item-007,item-011'),
    ('ing-pork-knuckle', 'item-008'),
    ('ing-peppercorns', 'item-008'),
    ('inv-002', 'item-009,item-010,item-011,item-012,item-016,item-021,item-022'),
    ('ing-lemongrass', 'item-009'),
    ('ing-annatto-oil', 'item-009,item-021'),
    ('ing-ginger', 'item-009,item-011,item-028'),
    ('ing-green-papaya', 'item-011'),
    ('ing-malunggay', 'item-011'),
    ('ing-green-peas', 'item-010'),
    ('ing-banana-ketchup', 'item-012,item-017'),
    ('ing-brown-sugar', 'item-012,item-018,item-022,item-026'),
    ('ing-bamboo-skewers', 'item-012'),
    ('ing-spanish-mackerel', 'item-013'),
    ('ing-sawsawan', 'item-013'),
    ('inv-004', 'item-014,item-015,item-016,item-021'),
    ('ing-butter', 'item-014,item-017'),
    ('ing-parsley', 'item-014'),
    ('ing-squid', 'item-015'),
    ('ing-scallops', 'item-015'),
    ('ing-mussels', 'item-015'),
    ('ing-egg-noodles', 'item-016,item-021'),
    ('ing-cabbage', 'item-016,item-024'),
    ('ing-snap-peas', 'item-016,item-024'),
    ('ing-oyster-sauce', 'item-016,item-024'),
    ('ing-elbow-macaroni', 'item-017'),
    ('ing-ground-beef', 'item-017'),
    ('ing-cheddar-cheese', 'item-017'),
    ('ing-milk', 'item-017'),
    ('ing-flour', 'item-017'),
    ('inv-007', 'item-018,item-022'),
    ('inv-005', 'item-006,item-018,item-022,item-025'),
    ('ing-coconut-cream', 'item-018'),
    ('ing-egg-yolks', 'item-019'),
    ('ing-condensed-milk', 'item-019,item-021'),
    ('ing-evaporated-milk', 'item-019,item-020,item-021'),
    ('ing-granulated-sugar', 'item-019'),
    ('ing-vanilla', 'item-019'),
    ('ing-mixed-vegetables', 'item-021,item-022'),
    ('ing-shaved-ice', 'item-020'),
    ('ing-sweetened-beans', 'item-020'),
    ('ing-jellies', 'item-020'),
    ('ing-kaong', 'item-020'),
    ('ing-macapuno', 'item-020'),
    ('ing-ube-halaya', 'item-020'),
    ('ing-ube-ice-cream', 'item-020'),
    ('ing-eggs', 'item-021,item-024'),
    ('ing-peanuts', 'item-022'),
    ('ing-ampalaya', 'item-023'),
    ('ing-okra', 'item-023'),
    ('ing-squash', 'item-023'),
    ('ing-cauliflower', 'item-024'),
    ('ing-quail-eggs', 'item-024'),
    ('ing-young-coconut', 'item-025'),
    ('ing-pandan-jelly', 'item-025'),
    ('ing-sugar', 'item-025'),
    ('ing-ice', 'item-025,item-026,item-027,item-028'),
    ('ing-sago-pearls', 'item-026'),
    ('ing-gulaman', 'item-026'),
    ('ing-water', 'item-026,item-027,item-028'),
    ('ing-calamansi-juice', 'item-027'),
    ('ing-cane-sugar', 'item-027'),
    ('ing-honey', 'item-028')
)
INSERT INTO public.menu_item_ingredients (menu_item_id, inventory_item_id)
SELECT menu.id, inventory.id
FROM ingredient_menu_links AS links
CROSS JOIN LATERAL unnest(string_to_array(links.menu_ids, ',')) AS linked_menu(menu_item_id)
JOIN public.menu_items AS menu ON menu.id = linked_menu.menu_item_id
JOIN public.inventory_items AS inventory ON inventory.id = links.ingredient_id
ON CONFLICT (menu_item_id, inventory_item_id) DO NOTHING;
